export enum Permission {
  USER_READ = 'USER_READ',
  USER_WRITE = 'USER_WRITE',

  ROLE_READ = 'ROLE_READ',
  ROLE_WRITE = 'ROLE_WRITE',

  ATTENDANCE_READ = 'ATTENDANCE_READ',
  ATTENDANCE_WRITE = 'ATTENDANCE_WRITE',

  ASSIGNMENT_READ = 'ASSIGNMENT_READ',
  ASSIGNMENT_WRITE = 'ASSIGNMENT_WRITE',

  GRADE_READ = 'GRADE_READ',
  GRADE_WRITE = 'GRADE_WRITE',

  TUITION_READ = 'TUITION_READ',
  TUITION_WRITE = 'TUITION_WRITE',

  CLASS_READ = 'CLASS_READ',
  CLASS_WRITE = 'CLASS_WRITE',

  REPORT_READ = 'REPORT_READ',

  /** S2-04: Danh mục chương trình đào tạo */
  PROGRAM_READ = 'PROGRAM_READ',
  PROGRAM_WRITE = 'PROGRAM_WRITE',
}

